name: Frontend Docker Deployment

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Copy project to EC2
      - name: Copy project files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.SERVER_USER }}/client-dashboard"

      # Step 3: Build and run Docker container on EC2
      - name: Build and run Docker container on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/client-dashboard

            # Generate dynamic image tag (timestamp + run number)
            IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${{ github.run_number }}

            echo "🚀 Building image: client-dashboard:${IMAGE_TAG}"

            # Stop and remove old container
            docker stop client-dashboard || true
            docker rm client-dashboard || true

            # Build new Docker image with dynamic tag
            docker build -t client-dashboard:${IMAGE_TAG} .

            # Run new container on port 3001
            docker run -d --name client-dashboard -p 3001:3001 client-dashboard:${IMAGE_TAG}

            echo "✅ Deployment complete with image tag: ${IMAGE_TAG}"
